#!/usr/bin/env python3
"""Permanent invariants for the SC004/SC014 split (corrected PROTOFORM pass).

Host-runnable (no foma/flookup/Docker). These tests protect the committed
evidence that the bundled PWGmcAiMonophthongization was split into two
production rules, using the Old-English-row PROTOFORM (the production input):

  SC014  PNWGmcUnstressedAiMonophthongization : {*ai} -> {*ē}
         (unstressed *ai, final AND nonfinal; Ringe-Taylor's rule, not merely
         word-final); head of EarlyEnglishLineChanges. TWO corpus applications:
         span (*spánnai -> spanne) and meed (*mízdai -> meorde).
  SC004  EAFAiMonophthongization              : {*ái} -> {*ā}
         (stressed/root *ái; Early Anglo-Frisian / North Sea Germanic); EAF
         corridor, after SC028 PNWGmcPreconsonantalXLoss; carries the SC036
         *soul* boundary. 24 corpus applications (23 attested + roe).

loam (*láimą) is a stressed SC004 case by its PROTOFORM; whine (*xwḯnaną) and
withy (*wḯθagą) carry no *ai in PROTOFORM and are not ai-monophthongization
cases (the previous PROTO-based report misclassified all three).

The foma behavior is regenerated by tools/build_sc004_component_behaviors_docker.sh
into the behavior TSV; here we assert the committed TSV, the PROTOFORM-based
component report, and the germanic.txt source composition.

Run: cd Germanic/tests && python3 -m unittest test_sc004_component_split
"""
from __future__ import annotations

import csv
import json
import re
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SC_DIR = REPO_ROOT / "Germanic/docs/sound_changes"
ORDER_TESTS = SC_DIR / "order_tests"
BEHAVIORS_TSV = ORDER_TESTS / "sc004_component_behaviors.tsv"
COMPONENT_REPORT = ORDER_TESTS / "sc004_component_application_report.tsv"
SUMMARY_JSON = SC_DIR / "cascade_baseline/cascade_baseline_summary.json"
FST_SOURCE = REPO_ROOT / "Germanic/fsts/germanic.txt"

# Re-frozen 2026-08-14 after the deliberate SC022 literal adjacent-mn correction
# (heaven -> *xébun, stem -> *stámniz; see audits/heaven-sc022-implementation-2026.md).
FROZEN_OUTPUTS_SHA = "a72bdeb8451039206ab0b90110547f50171c209d5b9c08c71219ed45df5165fc"


def _read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


class ComponentBehaviorTests(unittest.TestCase):
    """Assert the foma-observed component behaviors (committed evidence TSV)."""

    def setUp(self):
        self.assertTrue(BEHAVIORS_TSV.exists(),
                        f"missing {BEHAVIORS_TSV}; regenerate with "
                        "build_sc004_component_behaviors_docker.sh")
        self.rows = {r["probe_id"]: r for r in _read_tsv(BEHAVIORS_TSV)}

    def test_all_probes_pass(self):
        for pid, r in self.rows.items():
            self.assertEqual(r["pass"], "1",
                             f"probe {pid}: {r['input']} -> {r['output']} "
                             f"(expected {r['expected']})")

    def test_sc014_monophthongizes_unstressed_ai_final_and_nonfinal(self):
        # Ringe-Taylor's rule is unstressed *ai > *e in BOTH environments.
        for pid, exp in (("rt_final_dagai", "*d*a*g*ē"),
                         ("rt_nonfinal_berain", "*b*e*r*ē*n"),
                         ("rt_nonfinal_habaisi", "*h*a*b*ē*s*i"),
                         ("rt_nonfinal_godaimaz", "*g*ō*d*ē*m*a*z")):
            r = self.rows[pid]
            self.assertTrue(r["rule"].startswith("SC014_"))
            self.assertEqual(r["output"], exp, f"{pid}")

    def test_sc014_does_not_touch_stressed_ai(self):
        r = self.rows["sc014_leaves_stressed"]
        self.assertEqual(r["output"], r["input"],
                         "SC014 must not alter stressed *ái")

    def test_sc004_monophthongizes_stressed_ai(self):
        r = self.rows["sc004_stressed_stainaz"]
        self.assertTrue(r["rule"].startswith("SC004_"))
        self.assertEqual(r["output"], "*s*t*ā*n*a*z")

    def test_sc004_does_not_touch_unstressed_ai(self):
        r = self.rows["sc004_leaves_unstressed"]
        self.assertEqual(r["output"], r["input"],
                         "SC004 must not alter unstressed *ai")

    def test_corpus_span_is_sc014(self):
        r = self.rows["corpus_span_sc014"]
        self.assertEqual(r["input"], "*s*p*á*n*n*ai")
        self.assertEqual(r["output"], "*s*p*á*n*n*ē")

    def test_corpus_loam_is_stressed_sc004(self):
        r = self.rows["corpus_loam_sc004"]
        self.assertEqual(r["input"], "*l*ái*m*ą")
        self.assertEqual(r["output"], "*l*ā*m*ą")

    def test_corpus_whine_is_neither(self):
        for pid in ("corpus_whine_neither_sc014", "corpus_whine_neither_sc004"):
            r = self.rows[pid]
            self.assertEqual(r["output"], r["input"],
                             f"{pid}: whine has no *ai in PROTOFORM")

    def test_alias_reproduces_composition(self):
        self.assertEqual(self.rows["alias_unstressed_path"]["output"], "*s*p*á*n*n*ē")
        self.assertEqual(self.rows["alias_stressed_path"]["output"], "*s*t*ā*n*a*z")


class ComponentReportTests(unittest.TestCase):
    """PROTOFORM-based application inventory: corrected corpus load and the
    PROTO/PROTOFORM disagreements that broke the previous report."""

    def setUp(self):
        self.rows = _read_tsv(COMPONENT_REPORT)
        self.by_concept = {}
        for r in self.rows:
            self.by_concept.setdefault(r["concept"], []).append(r)

    def test_report_uses_protoform_as_production_field(self):
        for r in self.rows:
            self.assertIn(r["prod_field"], ("PROTOFORM", "PROTO(fallback)"))
            if r["PROTOFORM"]:
                self.assertEqual(r["prod_field"], "PROTOFORM",
                                 f"{r['concept']}: must use PROTOFORM when present")

    def test_sc014_has_two_corpus_applications(self):
        sc014 = [r for r in self.rows if r["sc014_applies"] == "yes"]
        concepts = sorted(r["concept"] for r in sc014)
        self.assertEqual(concepts, ["meed", "span"],
                         "SC014 corpus applications must be exactly span and meed")

    def test_sc004_has_24_applications_23_attested(self):
        sc004 = [r for r in self.rows if r["sc004_applies"] == "yes"]
        self.assertEqual(len(sc004), 24, "SC004 applies to 24 corpus rows")
        unattested = [r for r in sc004 if r["counterpart"] in ("", "-")]
        self.assertEqual([r["concept"] for r in unattested], ["roe"],
                         "exactly one SC004 row (roe) is unattested")

    def test_loam_is_stressed_sc004_by_protoform(self):
        loam = self.by_concept["loam"][0]
        self.assertEqual(loam["PROTOFORM"], "*láimą")
        self.assertEqual(loam["PROTO"], "*laimōn")
        self.assertEqual(loam["proto_protoform_disagree"], "yes")
        self.assertEqual(loam["sc004_applies"], "yes")
        self.assertEqual(loam["sc014_applies"], "no")

    def test_whine_and_withy_are_not_ai_cases(self):
        for concept in ("whine", "withy"):
            r = self.by_concept[concept][0]
            self.assertEqual(r["rewrite_applied"], "none",
                             f"{concept} PROTOFORM has no *ai")
            self.assertEqual(r["proto_protoform_disagree"], "yes")

    def test_span_and_meed_are_sc014_by_protoform(self):
        span = self.by_concept["span"][0]
        meed = self.by_concept["meed"][0]
        self.assertEqual(span["PROTOFORM"], "*spánnai")
        self.assertEqual(span["counterpart"], "spanne")
        self.assertEqual(span["sc014_applies"], "yes")
        self.assertEqual(meed["PROTOFORM"], "*mízdai")
        self.assertEqual(meed["counterpart"], "meorde")
        self.assertEqual(meed["sc014_applies"], "yes")


class ProductionCascadeTests(unittest.TestCase):
    """germanic.txt carries the corrected, historically cleaner definitions and
    preserves the frozen corpus outputs."""

    def setUp(self):
        self.src = FST_SOURCE.read_text(encoding="utf-8")

    def test_frozen_outputs_preserved(self):
        summary = json.loads(SUMMARY_JSON.read_text(encoding="utf-8"))
        self.assertEqual(summary["outputs_sha256"], FROZEN_OUTPUTS_SHA)
        self.assertEqual(summary["matched"], 373)
        self.assertEqual(summary["mismatched"], 7)

    def test_sc014_body_is_unrestricted_unstressed_ai(self):
        m = re.search(
            r"define PNWGmcUnstressedAiMonophthongization \[\s*\n\s*(.*?)\n\s*\];",
            self.src)
        self.assertIsNotNone(m, "cannot find SC014 define")
        body = m.group(1).strip()
        self.assertEqual(body, "{*ai} -> {*ē}",
                         "SC014 must be the unrestricted unstressed rule (no || _ .#.)")

    def test_sc004_body_is_stressed_only(self):
        m = re.search(
            r"define EAFAiMonophthongization \[\s*\n\s*(.*?)\n\s*\];",
            self.src)
        self.assertIsNotNone(m, "cannot find SC004 define")
        body = m.group(1).strip()
        self.assertEqual(body, "{*ái} -> {*ā}",
                         "SC004 must be stressed-only (no {*ai}->{*ā} nonfinal branch)")

    def test_no_active_nonfinal_ai_to_a_branch(self):
        active = [ln for ln in self.src.splitlines()
                  if "{*ai} -> {*ā}" in ln and not ln.lstrip().startswith("#")]
        self.assertEqual(active, [], "the {*ai}->{*ā} branch must not survive")

    def test_sc014_leads_early_english_line_changes(self):
        m = re.search(r"define EarlyEnglishLineChanges \[\s*\n\s*([A-Za-z0-9]+)", self.src)
        self.assertEqual(m.group(1), "PNWGmcUnstressedAiMonophthongization")

    def test_sc004_general_runs_after_sc028_in_both_branches(self):
        pat = re.compile(
            r"\.o\. PNWGmcPreconsonantalXLoss\b.*\n(?:\s*#.*\n)*\s*\.o\. EAFAiMonophthongization\b")
        self.assertGreaterEqual(len(pat.findall(self.src)), 2)

    def test_alias_is_not_composed(self):
        self.assertNotIn(".o. PWGmcAiMonophthongization", self.src)
        self.assertNotRegex(self.src, r"PWGmcAiMonophthongization\s+\.o\.")
        self.assertIn("define PWGmcAiMonophthongization", self.src)

    def test_obsolete_breve_ai_no_op_is_gone(self):
        active = [ln for ln in self.src.splitlines()
                  if "{*ăi}" in ln and not ln.lstrip().startswith("#")]
        self.assertEqual(active, [])


if __name__ == "__main__":
    unittest.main()
