#!/usr/bin/env python3
"""Permanent invariants for the SC004 Outcome-C split (SC014 + SC004).

Host-runnable (no foma/flookup/Docker). These tests protect the committed
evidence that the bundled PWGmcAiMonophthongization was split into two
production rules placed at their genuine historical stages:

  SC014  PNWGmcUnstressedAiMonophthongization : word-final unstressed *ai -> *e
         (Proto-Northwest Germanic, early); head of EarlyEnglishLineChanges;
         ZERO corpus applications.
  SC004  EAFAiMonophthongization              : general/root *ai/*ai(acute) -> *a
         (Early Anglo-Frisian / North Sea Germanic, later); EAF corridor, after
         SC028 PNWGmcPreconsonantalXLoss; carries the SC036 *soul* boundary.

The foma behavior itself is regenerated by
tools/build_sc004_component_behaviors_docker.sh into the behavior TSV; here we
assert the committed TSV and the germanic.txt source composition.

Run: cd Germanic/tests && python3 -m unittest test_sc004_component_split
"""
from __future__ import annotations

import csv
import json
import re
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SC_DIR = REPO_ROOT / "Germanic/docs/sound_changes"
ORDER_TESTS = SC_DIR / "order_tests"
BEHAVIORS_TSV = ORDER_TESTS / "sc004_component_behaviors.tsv"
COMPONENT_REPORT = ORDER_TESTS / "sc004_component_application_report.tsv"
MOVEMENT_PROOFS = ORDER_TESTS / "sc004_split_movement_proofs.md"
CHRONOLOGY_CARD = ORDER_TESTS / "chronology_cards/SC004-components-chronology.md"
SUMMARY_JSON = SC_DIR / "cascade_baseline/cascade_baseline_summary.json"
FST_SOURCE = REPO_ROOT / "Germanic/fsts/germanic.txt"

FROZEN_OUTPUTS_SHA = "aaf19ba919cafbe86ea59d482ce74d0944f541336e246da481a3f37b20da480e"


def _read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


class ComponentBehaviorTests(unittest.TestCase):
    """Assert the foma-observed component behaviors (committed evidence TSV)."""

    def setUp(self):
        self.assertTrue(BEHAVIORS_TSV.exists(),
                        f"missing {BEHAVIORS_TSV}; regenerate with "
                        "build_sc004_component_behaviors_docker.sh")
        self.rows = {r["probe_id"]: r for r in _read_tsv(BEHAVIORS_TSV)}

    def test_all_probes_pass(self):
        for pid, r in self.rows.items():
            self.assertEqual(r["pass"], "1",
                             f"probe {pid}: {r['input']} -> {r['output']} "
                             f"(expected {r['expected']})")
            self.assertEqual(r["output"], r["expected"], f"probe {pid} output drift")

    def test_sc014_maps_word_final_ai_to_e(self):
        r = self.rows["final_ai_to_e"]
        self.assertTrue(r["rule"].startswith("SC014_"))
        self.assertEqual(r["input"], "*s*p*a*n*n*ai")
        self.assertEqual(r["output"], "*s*p*a*n*n*ē")

    def test_sc014_does_not_do_general_ai_to_a(self):
        # SC014 leaves both a stressed root *ai(acute) and an unaccented nonfinal
        # *ai untouched (it targets word-final position only).
        for pid in ("sc014_leaves_stressed", "sc014_leaves_nonfinal"):
            r = self.rows[pid]
            self.assertTrue(r["rule"].startswith("SC014_"))
            self.assertEqual(r["output"], r["input"],
                             f"{pid}: SC014 must not alter {r['input']}")

    def test_sc004_maps_stressed_ai_to_a(self):
        r = self.rows["sc004_stressed_ai_to_a"]
        self.assertTrue(r["rule"].startswith("SC004_"))
        self.assertEqual(r["input"], "*s*ái*w*a*l*ō")
        self.assertEqual(r["output"], "*s*ā*w*a*l*ō")

    def test_sc004_handles_two_unaccented_cases(self):
        # loam and whine: the two corpus protoforms whose *ai carries no accent
        # and is routed through the unaccented (nonfinal) rewrite.
        loam = self.rows["sc004_loam_nonfinal"]
        whine = self.rows["sc004_whine_nonfinal"]
        self.assertEqual(loam["output"], "*l*ā*m*ō*n")
        self.assertEqual(whine["output"], "*w*ā*n*ō*j*a*n*ą")

    def test_sc004_leaves_word_final_ai(self):
        # Clean separation: SC004 (nonfinal/stressed only) must not consume the
        # word-final unstressed *ai that SC014 owns.
        r = self.rows["sc004_leaves_final"]
        self.assertEqual(r["output"], "*s*p*a*n*n*ai")

    def test_alias_reproduces_bundled_relation(self):
        # The retained compatibility alias PWGmcAiMonophthongization == A.o.(B.o.C).
        self.assertEqual(self.rows["alias_final_path"]["output"], "*s*p*a*n*n*ē")
        self.assertEqual(self.rows["alias_stressed_path"]["output"], "*s*ā*w*a*l*ō")
        self.assertEqual(self.rows["alias_nonfinal_path"]["output"], "*l*ā*m*ō*n")


class CorpusLoadTests(unittest.TestCase):
    """SC014 zero corpus load; SC004 carries all witnesses; 25/26 reconciliation."""

    def setUp(self):
        self.rows = _read_tsv(COMPONENT_REPORT)

    def test_sc014_has_zero_corpus_load(self):
        a_rows = [r for r in self.rows
                  if "A_final_ai_to_e" in r["components_applied"]]
        self.assertEqual(a_rows, [],
                         "SC014 (Component A, word-final *ai -> *e) must have zero "
                         "corpus applications")

    def test_sc004_carries_all_witnesses(self):
        comps = [r["components_applied"] for r in self.rows]
        self.assertEqual(sum("B_nonfinal_ai_to_a" in c for c in comps), 2)
        self.assertEqual(sum("C_stressed_ai_to_a" in c for c in comps), 24)
        self.assertEqual(len(self.rows), 26, "26 corpus protoforms carry *ai/*ái")

    def test_soul_is_a_stressed_sc004_witness(self):
        soul = [r for r in self.rows if r["concept"] == "soul"]
        self.assertEqual(len(soul), 1)
        self.assertIn("C_stressed_ai_to_a", soul[0]["components_applied"])
        self.assertEqual(soul[0]["after_full_sc004"], "*s*ā*w*a*l*ō")

    def test_25_26_reconciliation_is_the_unattested_roe(self):
        # 26 corpus protoforms; 25 attested. The single unattested one is roe
        # (*ráixōn, COUNTERPART = -), a genuine Component C application.
        unattested = [r for r in self.rows if r["expected_oe"] in ("", "-")]
        self.assertEqual([r["concept"] for r in unattested], ["roe"],
                         "the 26->25 gap must be exactly the unattested roe")


class EvidenceDocTests(unittest.TestCase):
    """The prose evidence records the frozen checksum, the 25/26 gap, and the
    SC036 *soul* boundary attributed to SC004 (not SC014)."""

    def test_movement_proofs_record_frozen_checksum_and_count(self):
        text = MOVEMENT_PROOFS.read_text(encoding="utf-8")
        self.assertIn("aaf19ba9", text, "movement proofs must cite the frozen checksum")
        self.assertIn("25 vs 26", text, "movement proofs must reconcile 25 vs 26")

    def test_chronology_card_attributes_sc036_boundary_to_general(self):
        text = CHRONOLOGY_CARD.read_text(encoding="utf-8")
        self.assertIn("SC036", text)
        self.assertIn("soul", text)
        # SC014 / Component A has no positive boundary.
        self.assertRegex(text, r"Component A[\s\S]*Corpus applications:\*\*\s*`0`")


class ProductionCascadeTests(unittest.TestCase):
    """The production germanic.txt places the two components at their genuine
    stages and preserves the frozen corpus outputs."""

    def setUp(self):
        self.src = FST_SOURCE.read_text(encoding="utf-8")

    def test_frozen_outputs_preserved(self):
        summary = json.loads(SUMMARY_JSON.read_text(encoding="utf-8"))
        self.assertEqual(summary["outputs_sha256"], FROZEN_OUTPUTS_SHA,
                         "combined production cascade must preserve every lexical output")
        self.assertEqual(summary["matched"], 372)
        self.assertEqual(summary["mismatched"], 8)

    def test_sc014_leads_early_english_line_changes(self):
        m = re.search(r"define EarlyEnglishLineChanges \[\s*\n\s*([A-Za-z0-9]+)", self.src)
        self.assertIsNotNone(m, "cannot locate EarlyEnglishLineChanges head")
        self.assertEqual(m.group(1), "PNWGmcUnstressedAiMonophthongization",
                         "SC014 must lead EarlyEnglishLineChanges (its old SC004 slot)")

    def test_sc004_general_runs_in_eaf_corridor_after_sc028(self):
        # EAFAiMonophthongization is composed immediately after
        # PNWGmcPreconsonantalXLoss (SC028) in both pipeline branches.
        pat = re.compile(
            r"\.o\. PNWGmcPreconsonantalXLoss\b.*\n(?:\s*#.*\n)*\s*\.o\. EAFAiMonophthongization\b")
        self.assertGreaterEqual(len(pat.findall(self.src)), 2,
                                "SC004 general must follow SC028 in both branches")

    def test_alias_is_not_composed_in_any_pipeline(self):
        # PWGmcAiMonophthongization survives only as a standalone define; it must
        # never be composed with `.o.` into a pipeline.
        self.assertNotIn(".o. PWGmcAiMonophthongization", self.src)
        self.assertNotRegex(self.src, r"PWGmcAiMonophthongization\s+\.o\.")
        self.assertIn("define PWGmcAiMonophthongization", self.src)

    def test_obsolete_breve_ai_no_op_is_gone(self):
        # The old SC014 no-op rewrite {*ăi} -> {*ē} must no longer exist as an
        # active rule. A historical mention in a comment line is allowed.
        active = [ln for ln in self.src.splitlines()
                  if "{*ăi}" in ln and not ln.lstrip().startswith("#")]
        self.assertEqual(active, [],
                         "the breve-marked {*ăi} no-op must not survive as an active rule")


if __name__ == "__main__":
    unittest.main()
