#!/usr/bin/env python3
"""Temporary first-break harness for bundled early rules SC002 and SC003."""

from __future__ import annotations

import argparse
import csv
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Sequence


SCRIPT_PATH = Path(__file__).resolve()
ORDER_TESTS_DIR = SCRIPT_PATH.parent
GERMANIC_DIR = ORDER_TESTS_DIR.parents[2]
TOOLS_DIR = GERMANIC_DIR / "tools"
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

import sound_change_order_sensitivity as sos  # noqa: E402


RULE_LINE_PREFIX = ".o."
SUPPORTED_CHANGE_IDS = {"SC002", "SC003"}


def repo_paths() -> dict[str, Path]:
    defaults = sos.repo_paths()
    summaries_dir = ORDER_TESTS_DIR / "summaries"
    defaults.update(
        {
            "order_tests_dir": ORDER_TESTS_DIR,
            "summaries_dir": summaries_dir,
            "early_first_break_tsv": summaries_dir / "order_sensitivity_first_break_early_rules_01.tsv",
            "early_first_break_changes_tsv": summaries_dir / "order_sensitivity_first_break_early_rules_01_changes.tsv",
            "early_first_break_failures_tsv": summaries_dir / "order_sensitivity_first_break_early_rules_01_failures.tsv",
        }
    )
    return defaults


def parse_args() -> argparse.Namespace:
    defaults = repo_paths()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--change", required=True, help="Target SC id, e.g. SC002 or SC003")
    parser.add_argument("--direction", choices=("earlier", "later", "both"), default="both")
    parser.add_argument("--resume", action="store_true", help="Resume an interrupted first-break crawl")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate imports, target lookup, witness selection, and temporary expanded-cascade construction without compiling or evaluating variants.",
    )
    parser.add_argument("--inventory", default=str(defaults["inventory"]))
    parser.add_argument("--germanic", default=str(defaults["germanic_txt"]))
    parser.add_argument("--sandbox", default=str(defaults["sandbox_txt"]))
    parser.add_argument("--tsv", default=str(defaults["aligned_tsv"]))
    parser.add_argument("--bin", default=str(defaults["live_bin"]))
    parser.add_argument("--summary-output", default=str(defaults["early_first_break_tsv"]))
    parser.add_argument("--changes-output", default=str(defaults["early_first_break_changes_tsv"]))
    parser.add_argument("--failures-output", default=str(defaults["early_first_break_failures_tsv"]))
    args = parser.parse_args()
    args.change = args.change.upper()
    if args.change not in SUPPORTED_CHANGE_IDS:
        parser.error("--change must be SC002 or SC003 for the current early-rule harness")
    return args


def parse_expanded_order_from_sandbox(sandbox_path: Path) -> list[str]:
    order: list[str] = []
    for raw_line in sandbox_path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.split("#", 1)[0].strip()
        if not stripped.startswith(RULE_LINE_PREFIX):
            continue
        rule = stripped.removeprefix(RULE_LINE_PREFIX).strip()
        if not rule.endswith(";"):
            continue
        order.append(rule[:-1].strip())
    if not order:
        raise RuntimeError(f"Failed to recover any explicit rule order from {sandbox_path}")
    return order


def build_expanded_variant_appendix(order: Sequence[str]) -> str:
    lines = [
        "",
        "# Variant full explicit Old English order generated by run_early_rule_first_breaks.py",
        "define VariantExpandedOldEnglishReflexes EnglishProtoInput",
    ]
    for rule in order:
        lines.append(f"    .o. {rule}")
    lines.extend(
        [
            "    ;",
            "",
            "clear stack",
            "regex VariantExpandedOldEnglishReflexes;",
            "save stack old_english_variant.bin",
            "",
        ]
    )
    return "\n".join(lines)


def dry_run_preview(
    *,
    change: sos.ChangeInfo,
    explicit_order: Sequence[str],
    rows: Sequence[dict[str, str]],
    germanic_path: Path,
) -> None:
    inventory_examples: list[str] = []
    inventory_path = repo_paths()["inventory"]
    with inventory_path.open(encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        for row in reader:
            if (row.get("change_id") or "").strip() != change.change_id:
                continue
            inventory_examples = [
                item.strip()
                for item in (row.get("example_lexemes") or "").split(",")
                if item.strip()
            ]
            break
    explicit_index = explicit_order.index(change.rule_name) + 1
    earlier_rule = explicit_order[explicit_index - 2] if explicit_index > 1 else "START_OF_EXPLICIT_CHAIN"
    later_rule = explicit_order[explicit_index] if explicit_index < len(explicit_order) else "END_OF_EXPLICIT_CHAIN"
    appendix = build_expanded_variant_appendix(explicit_order)
    with tempfile.TemporaryDirectory(prefix=f"{change.change_id.lower()}_dryrun_") as temp_dir:
        tmpdir = Path(temp_dir)
        tmp_germanic = tmpdir / "germanic.txt"
        shutil.copy2(germanic_path, tmp_germanic)
        with tmp_germanic.open("a", encoding="utf-8") as handle:
            handle.write(appendix)
        print(f"dry_run_change={change.change_id}")
        print(f"inventory_order={change.current_order}")
        print(f"explicit_chain_position={explicit_index}")
        print(f"earlier_neighbor={earlier_rule}")
        print(f"later_neighbor={later_rule}")
        print(f"witness_candidates={', '.join(inventory_examples) if inventory_examples else '(none recorded)'}")
        print(f"corpus_rows={len(rows)}")
        print(f"temporary_germanic_built=yes")
        print(f"temporary_appendix_bytes={len(appendix.encode('utf-8'))}")


def main() -> None:
    args = parse_args()
    inventory_path = Path(args.inventory)
    germanic_path = Path(args.germanic)
    sandbox_path = Path(args.sandbox)
    tsv_path = Path(args.tsv)
    live_bin_path = Path(args.bin)
    summary_output = Path(args.summary_output)
    changes_output = Path(args.changes_output)
    failures_output = Path(args.failures_output)

    inventory_by_id, ordered_inventory = sos.load_inventory(inventory_path)
    change = inventory_by_id[args.change]
    explicit_order = parse_expanded_order_from_sandbox(sandbox_path)
    if change.rule_name not in explicit_order:
        raise RuntimeError(
            f"{change.rule_name} is not exposed as an explicit stage in old_english_sandbox.txt; cannot test {change.change_id}"
        )

    rows = sos.load_rows(tsv_path)
    if args.dry_run:
        dry_run_preview(
            change=change,
            explicit_order=explicit_order,
            rows=rows,
            germanic_path=germanic_path,
        )
        return

    baseline_results = sos.evaluate_rows(rows, live_bin_path)
    original_builder = sos.build_variant_appendix
    try:
        sos.build_variant_appendix = build_expanded_variant_appendix
        sos.run_first_break(
            change=change,
            live_order=explicit_order,
            rows=rows,
            baseline_results=baseline_results,
            ordered_inventory=ordered_inventory,
            summary_output=summary_output,
            changes_output=changes_output,
            failures_output=failures_output,
            germanic_path=germanic_path,
            sandbox_path=sandbox_path,
            direction_mode=args.direction,
            resume=args.resume,
        )
    finally:
        sos.build_variant_appendix = original_builder


if __name__ == "__main__":
    main()
